plugins {
	id 'java'
	id 'maven-publish'
}

version = project.plugin_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven {
		name = 'papermc'
		url = uri('https://repo.papermc.io/repository/maven-public/')
	}
}

dependencies {
	compileOnly "io.papermc.paper:paper-api:${project.paper_api_version}"
}

processResources {
	def pluginVersion = project.version
	def apiVersion = project.minecraft_version
	inputs.property 'version', pluginVersion
	inputs.property 'apiVersion', apiVersion

	filesMatching('plugin.yml') {
		expand 'version': pluginVersion, 'apiVersion': apiVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			from components.java
		}
	}
}
